### ISSUE TITLE
OCD Job Loop

### ISSUE THREAD

**Issue by MrXarous** [emipa606/RFRimDisorders#4]
User left a DM with a log stating "the pawn has an ocd to clean and they are currently in the mental break" causing a job looping issue where the pawn never does anything, just breaks. Seems in game it showed the pawn just picking up water to drink and dropping it over and over. Log showed something slightly different, but it's modded gameplay and I have yet to reproduce in a vanilla-like setting. 

https://gist.github.com/08886796407716eed31d28a13118af10

**Comment by emipa606** [comment]
Yea, I cant reproduce it in vanilla either

**Comment by Noxilie** [comment]
Can reproduce it with Cleaning Priority (Continued) - https://github.com/emipa606/CleaningPriority
_So, basically I enabled debug log for the job (pawn.jobs.debugLog = true) and it became obvious._

What is happening:
1) `StartJob [Clean (Job_3158) A = Thing_Filth_RubbleRock7345] lastJobEndCondition=InterruptForced, jobGiver=, cancelBusyStances=True `
we entered MentalStateTick() here and started a new job

2) `CleanupCurrentJob Clean_Prioritized condition InterruptForced`
some job which is not JobDefOf.Clean is forcefully interrupted because of JobCondition.InterruptForced in StartJob call, that's **not the case** of our problem though

3) `JobDriver_CleanFilth ends current job Clean (Job_3158) A = Thing_Filth_RubbleRock7345 because of toil SucceedOnNoTargetInQueue at toils[1].endConditions[0]`
Here we are. Clean job is succeeding without even starting, because in **JobDriver_CleanFilth.MakeNewToils()** we are calling **Toils_JobTransforms.ClearDespawnedNullOrForbiddenQueuedTargets(TargetIndex.A)** which is trying to make a new toil by removing all invalid targets from a queue... but our queue TargetIndex.A is empty. So, empty queue -> no toil -> job ends :)

You can look in WorkGiver_CleanFilth class for a proper way to create a new job

        public override Job JobOnThing(Pawn pawn, Thing t, bool forced = false)
        {
                Job job = JobMaker.MakeJob(JobDefOf.Clean);
                job.AddQueuedTarget(TargetIndex.A, t);


We need to call AddQueuedTarget for our job (or just add our target to the queue by ourselves) to not to trigger an infinite loop here.
Like this:

            var filthInHomeArea = pawn.Map.listerFilthInHomeArea?.FilthInHomeArea.Where(thing =>
                pawn.CanReserveAndReach(thing, PathEndMode.ClosestTouch, Danger.Some));
            if (filthInHomeArea?.Any() == true)
            {
                Job clnJob = new Job(JobDefOf.Clean)
                {
                    locomotionUrgency = LocomotionUrgency.Sprint
                };
                clnJob.AddQueuedTarget(TargetIndex.A, filthInHomeArea.RandomElement());
                pawn.jobs.StartJob(clnJob, JobCondition.InterruptForced);
                base.MentalStateTick();
                return;
            }

**Comment by emipa606** [comment]
Fixed with #7
